services:
  postgres:
    container_name: ref_system.postgres
    image: postgres:16.4
    hostname: postgres
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U dev -d ref_system'"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
  api-up:
    env_file:
      - .env.dev
    environment:
      - API_CONTAINER_NAME=${API_NAME}
      - API_PORT=${API_PORT}
      - POSTGRES_DSN=${POSTGRES_DSN}
    container_name: ref_system.api
    build:
      context: .
      dockerfile: dockerfile.api
    image: donskova1ex/api:latest
    ports:
      - 8080:${API_PORT}
    volumes:
      - .env.dev:/app/.env.dev
    working_dir: /app
    depends_on:
      - postgres